---
matrix:
  include:
    - IMAGE: 3.6-stretch
      TOXENV: py36

    - IMAGE: 3.7-stretch
      TOXENV: py37

    - IMAGE: 3.8-buster
      TOXENV: py38

    - IMAGE: 3.9-buster
      TOXENV: py39

    - IMAGE: 3.9-buster
      TOXENV: lint

    - IMAGE: 3.9-buster
      TOXENV: sort

    - IMAGE: 3.9-buster
      TOXENV: format

    - IMAGE: 3.9-buster
      TOXENV: type

pipeline:
  build:
    image: python:${IMAGE}
    commands:
      - pip install tox
      - tox -e ${TOXENV}

kind: pipeline
name: code coverage
steps:
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
