---
matrix:
  include:
    - IMAGE: 3.9-buster
      TOXENV: lint
    - IMAGE: 3.9-buster
      TOXENV: sort
    - IMAGE: 3.9-buster
      TOXENV: format
    - IMAGE: 3.9-buster
      TOXENV: type

pipeline:
  build:
    image: python:${IMAGE}
    commands:
      - pip install tox
      - tox -e ${TOXENV}
